# Generated by Django 4.2.7 on 2025-12-23 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fair_agent_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trace_id", models.CharField(max_length=100, unique=True)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("duration_ms", models.FloatField(default=0.0)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField(blank=True, null=True)),
                ("duration_ms", models.FloatField(default=0.0)),
                ("status", models.CharField(default="running", max_length=50)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "trace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spans",
                        to="fair_agent_app.tracelog",
                    ),
                ),
            ],
        ),
    ]
