# FAIR-Agent Configuration
# Configuration file for FAIR-Agent system components

# Model Configuration
models:
  finance:
    name: "meta-llama/Llama-2-7b-hf"
    alternative: "microsoft/DialoGPT-large"
    device: "auto"
    max_length: 512
    temperature: 0.7
    
  medical:
    name: "microsoft/BioGPT-Large"
    alternative: "dmis-lab/biobert-v1.1"
    device: "auto"
    max_length: 512
    temperature: 0.3

# Dataset Configuration
datasets:
  finance:
    - name: "finqa"
      source: "ibm-research/finqa"
      local_path: "./datasets/finance/finqa"
      preprocessing_required: true
    - name: "tatqa"
      source: "NExTplusplus/tat-qa"
      local_path: "./datasets/finance/tatqa"
      preprocessing_required: true
    - name: "convfinqa"
      source: "ibm-research/convfinqa"
      local_path: "./datasets/finance/convfinqa"
      preprocessing_required: true
      
  medical:
    - name: "mimiciv"
      source: "physionet/mimiciv"
      local_path: "./datasets/medical/mimiciv"
      preprocessing_required: true
      access_required: true
    - name: "pubmedqa"
      source: "pubmedqa/pubmedqa"
      local_path: "./datasets/medical/pubmedqa"
      preprocessing_required: true
    - name: "medmcqa"
      source: "medmcqa/medmcqa"
      local_path: "./datasets/medical/medmcqa"
      preprocessing_required: false

# Orchestrator Configuration
orchestrator:
  enable_cross_domain: true
  confidence_threshold: 0.5
  max_retries: 3
  timeout_seconds: 30
  
# Evaluation Configuration
evaluation:
  metrics:
    - faithfulness
    - calibration
    - robustness
    - safety
    - interpretability
  
  faithfulness:
    method: "token_overlap"
    threshold: 0.7
    
  calibration:
    method: "confidence_accuracy"
    bins: 10
    
  robustness:
    perturbation_types:
      - "synonym_replacement"
      - "random_insertion"
      - "random_deletion"
    perturbation_ratio: 0.1
    
  safety:
    enable_medical_safety: true
    enable_financial_risk: true
    safety_keywords_file: "./config/safety_keywords.yaml"

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "./logs/fair_agent.log"
  max_file_size: "10MB"
  backup_count: 5

# API Configuration (for future extensions)
api:
  host: "localhost"
  port: 8000
  enable_cors: true
  rate_limit: 100  # requests per minute

# Cache Configuration
cache:
  enable: true
  type: "file"  # options: file, redis, memory
  path: "./cache"
  ttl_seconds: 3600  # 1 hour

# Security Configuration
security:
  enable_input_validation: true
  max_query_length: 1000
  blocked_patterns:
    - "harmful medical advice"
    - "financial manipulation"
  enable_content_filtering: true