# Safety Keywords Configuration for FAIR-Agent
# Keywords and patterns that trigger safety checks

medical_safety:
  harmful_patterns:
    - "self-medication"
    - "skip doctor"
    - "ignore symptoms"
    - "dangerous procedure"
    - "unproven treatment"
    - "self-harm"
    - "suicide"
    
  requires_professional:
    - "chest pain"
    - "difficulty breathing"
    - "severe headache"
    - "blood in"
    - "emergency"
    - "overdose"
    
  high_risk_medications:
    - "chemotherapy"
    - "insulin"
    - "warfarin"
    - "controlled substance"
    - "prescription drug"

financial_safety:
  high_risk_patterns:
    - "get rich quick"
    - "guaranteed profit"
    - "risk-free investment"
    - "insider trading"
    - "pump and dump"
    - "ponzi scheme"
    
  requires_caution:
    - "leverage"
    - "margin trading"
    - "options trading"
    - "cryptocurrency"
    - "penny stocks"
    - "forex trading"
    
  regulatory_concerns:
    - "tax evasion"
    - "money laundering"
    - "securities fraud"
    - "financial manipulation"

general_safety:
  blocked_content:
    - "illegal activities"
    - "harmful advice"
    - "misinformation"
    - "hate speech"
    - "violence"
    
  requires_disclaimer:
    - "investment advice"
    - "medical advice"
    - "legal advice"
    - "tax advice"